### ISSUE TITLE
Refactoring and Documentation (Code Review)

### ISSUE THREAD

**Issue by braddotcoffee** [GavBog/FROSTore#1]
## Documentation
* It's fine to have a lot of comments in your documentation/example code
* Your examples are the real "entrypoint" for someone interested in potentially using this library
* Because of that, you shouldn't assume that they're looking at the code in their editor - they're probably just clicking through on GitHub
* We need the code and the comments to be its own self contained package
* It also might really help you to come up with a "Quickstart"
  * Just by virtue of having to type this out in markdown you may lower the barrier of entry to your library 

## Many Blocks / Deeply Nested Code / Too Many Params
* I think all of these are symptoms of the same "problem"
* It seems like you're very comfortable increasing complexity of your current "scope" in order to prevent having to context switch
* As soon as you hit the point where your "feature" is done / you know what's required of the code you should try to take a step back and look from a top down perspective on what you've just created
  * How would someone new to the codebase internalize what I just wrote?
  * Will it be annoying for me to find the thing that I need to change in the future?

**Comment by GavBog** [comment]
Thanks a ton for the review!
The codebase has become much more manageable after refactoring and implementing some of your recommendations. 😄

Fixed in https://github.com/GavBog/FROSTore/commit/c4c76fb2baffd078a253eaeb6c63c51ca77e9974
